### ISSUE TITLE
Code release date?

### ISSUE THREAD

**Issue by LetiP** [copenlu/nle_faithfulness#1]
Hi congrats for this work! It's very interesting. When do you plan to publish the code? :slightly_smiling_face:

**Comment by apepa** [comment]
Hello, thank you so much for your interest! As I am currently on maternity leave, I plan to publish the code once I am back in September. I apologize for any inconvenience this delay may cause, but I want to ensure I can give it the attention and thoroughness it deserves. Thank you for your understanding, and I look forward to sharing the code with you in September! 🙂

**Comment by apepa** [comment]
This is now released :)

**Comment by LetiP** [comment]
Thanks a lot! 👍
